"""weight collection added

Revision ID: 086b6fba34b9
Revises: 2382aabd9e76
Create Date: 2026-03-01 21:37:46.535291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086b6fba34b9'
down_revision = '2382aabd9e76'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('weight_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_weight_collections_animal_id'), 'weight_collections', ['animal_id'], unique=False)
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_collections_animal_id'), table_name='weight_collections')
    op.drop_table('weight_collections')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###