"""add purchase_date to animals

Revision ID: 0b05fe1d3572
Revises: a8bd165fcb99
Create Date: 2025-12-24 15:45:51.448937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b05fe1d3572'
down_revision = 'a8bd165fcb99'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
