"""event total price added

Revision ID: 0bfa2c575ba4
Revises: a153f587a4fd
Create Date: 2026-02-11 11:26:19.894967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfa2c575ba4'
down_revision = 'a153f587a4fd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_events', sa.Column('total_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_animal_events_total_price'), 'animal_events', ['total_price'], unique=False)
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_events_total_price'), table_name='animal_events')
    op.drop_column('animal_events', 'total_price')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###