"""milk collection table added e

Revision ID: 2382aabd9e76
Revises: 282ae4a50a36
Create Date: 2026-02-20 14:42:21.528500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2382aabd9e76'
down_revision = '282ae4a50a36'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###