"""milk collection table added

Revision ID: 282ae4a50a36
Revises: 0bfa2c575ba4
Create Date: 2026-02-20 13:18:18.829866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282ae4a50a36'
down_revision = '0bfa2c575ba4'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('collection_time', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('milk_snf', sa.Float(), nullable=True),
    sa.Column('milk_fat', sa.Float(), nullable=True),
    sa.Column('milk_water', sa.Float(), nullable=True),
    sa.Column('milk_session', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_milk_collections_animal_id'), 'milk_collections', ['animal_id'], unique=False)
    op.create_index(op.f('ix_milk_collections_milk_fat'), 'milk_collections', ['milk_fat'], unique=False)
    op.create_index(op.f('ix_milk_collections_milk_session'), 'milk_collections', ['milk_session'], unique=False)
    op.create_index(op.f('ix_milk_collections_milk_snf'), 'milk_collections', ['milk_snf'], unique=False)
    op.create_index(op.f('ix_milk_collections_milk_water'), 'milk_collections', ['milk_water'], unique=False)
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milk_collections_milk_water'), table_name='milk_collections')
    op.drop_index(op.f('ix_milk_collections_milk_snf'), table_name='milk_collections')
    op.drop_index(op.f('ix_milk_collections_milk_session'), table_name='milk_collections')
    op.drop_index(op.f('ix_milk_collections_milk_fat'), table_name='milk_collections')
    op.drop_index(op.f('ix_milk_collections_animal_id'), table_name='milk_collections')
    op.drop_table('milk_collections')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###