"""fields added to material table

Revision ID: 28f062286d7b
Revises: b740f4fb4a40
Create Date: 2025-12-27 09:05:59.386448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28f062286d7b'
down_revision = 'b740f4fb4a40'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('inventory_moved_date', sa.Date(), nullable=True))
    op.alter_column('animals', 'status',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.Enum('alive', 'sold', 'dead', 'transferred', 'in_inventory', name='animalstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'alive'"))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'status',
               existing_type=sa.Enum('alive', 'sold', 'dead', 'transferred', 'in_inventory', name='animalstatus', native_enum=False),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("'alive'"))
    op.drop_column('animals', 'inventory_moved_date')
    # ### end Alembic commands ###
