"""master animal table

Revision ID: 357e49f7cdcc
Revises: 5826a03d0754
Create Date: 2025-12-31 10:49:24.058061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357e49f7cdcc'
down_revision = '5826a03d0754'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
