"""created by added

Revision ID: 3c7cd980e481
Revises: bbd3e3f49681
Create Date: 2026-02-03 21:56:21.713831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c7cd980e481'
down_revision = 'bbd3e3f49681'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('animal_events', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('animal_events', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('animal_inventory_moves', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('animal_inventory_moves', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('animal_tracking', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('animal_tracking', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_animal_tracking_tag_id'), table_name='animal_tracking')
    op.create_index(op.f('ix_animal_tracking_tag_id'), 'animal_tracking', ['tag_id'], unique=False)
    op.create_unique_constraint('uq_animal_tracking_tag_id_created_by', 'animal_tracking', ['tag_id', 'created_by'])
    op.alter_column('customers', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('deliveries', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('deliveries', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.alter_column('inventory', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('order_items', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('order_verification_tokens', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('order_verification_tokens', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('token'), table_name='order_verification_tokens')
    op.create_unique_constraint('uq_order_verification_tokens_token_created_by', 'order_verification_tokens', ['token', 'created_by'])
    op.add_column('orders', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('order_number'), table_name='orders')
    op.create_unique_constraint('uq_orders_order_number_created_by', 'orders', ['order_number', 'created_by'])
    op.add_column('payments', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('payments', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('purchase_raw_materials', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('purchase_raw_materials', sa.Column('updated_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_raw_materials', 'updated_by')
    op.drop_column('purchase_raw_materials', 'created_by')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_constraint('uq_orders_order_number_created_by', 'orders', type_='unique')
    op.create_index(op.f('order_number'), 'orders', ['order_number'], unique=True)
    op.drop_column('orders', 'updated_by')
    op.drop_column('orders', 'created_by')
    op.drop_constraint('uq_order_verification_tokens_token_created_by', 'order_verification_tokens', type_='unique')
    op.create_index(op.f('token'), 'order_verification_tokens', ['token'], unique=True)
    op.drop_column('order_verification_tokens', 'updated_by')
    op.drop_column('order_verification_tokens', 'created_by')
    op.drop_column('order_items', 'updated_by')
    op.drop_column('order_items', 'created_by')
    op.alter_column('inventory', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('deliveries', 'updated_by')
    op.drop_column('deliveries', 'created_by')
    op.alter_column('customers', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('uq_animal_tracking_tag_id_created_by', 'animal_tracking', type_='unique')
    op.drop_index(op.f('ix_animal_tracking_tag_id'), table_name='animal_tracking')
    op.create_index(op.f('ix_animal_tracking_tag_id'), 'animal_tracking', ['tag_id'], unique=True)
    op.drop_column('animal_tracking', 'updated_by')
    op.drop_column('animal_tracking', 'created_by')
    op.drop_column('animal_inventory_moves', 'updated_by')
    op.drop_column('animal_inventory_moves', 'created_by')
    op.drop_column('animal_events', 'updated_by')
    op.drop_column('animal_events', 'created_by')
    op.drop_column('addresses', 'updated_by')
    op.drop_column('addresses', 'created_by')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###