"""fields added to material table

Revision ID: 3d1efdbe9fe5
Revises: f61b333fb382
Create Date: 2025-12-26 21:00:54.172567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1efdbe9fe5'
down_revision = 'f61b333fb382'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_raw_materials', sa.Column('material_name', sa.Text(), nullable=False))
    op.add_column('purchase_raw_materials', sa.Column('material_expiry_date', sa.Date(), nullable=True))
    op.add_column('purchase_raw_materials', sa.Column('batch_number', sa.Text(), nullable=True))
    op.add_column('purchase_raw_materials', sa.Column('supplier', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_raw_materials', 'supplier')
    op.drop_column('purchase_raw_materials', 'batch_number')
    op.drop_column('purchase_raw_materials', 'material_expiry_date')
    op.drop_column('purchase_raw_materials', 'material_name')
    # ### end Alembic commands ###
