"""updated_at changes on 29_nov_2025 1030AM

Revision ID: 48572dc17c2d
Revises: ddbe992a8055
Create Date: 2025-11-29 10:39:27.926781

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '48572dc17c2d'
down_revision = 'ddbe992a8055'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inventory', ['animal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    # ### end Alembic commands ###
