"""init multi db

Revision ID: 5917932b2449
Revises: fc509e769231
Create Date: 2025-12-23 20:53:39.441286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5917932b2449'
down_revision = 'fc509e769231'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_animal_events_animal_id'), 'animal_events', ['animal_id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('birth', 'purchase', name='animalsource'), nullable=True),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('alive', 'sold', 'dead', 'transferred', name='animalstatus'), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=True)
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_animal_events_animal_id'), table_name='animal_events')
    op.drop_table('animal_events')
    # ### end Alembic commands ###
