"""updated at and nullable set on 24_12_2025

Revision ID: 6141d38f2700
Revises: 0a530aef8447
Create Date: 2025-12-24 14:43:07.750978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6141d38f2700'
down_revision = '0a530aef8447'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('animals', 'tag_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('animals', 'species',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('animals', 'breed',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('animals', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('animals', 'source',
               existing_type=mysql.ENUM('birth', 'purchase'),
               nullable=False)
    op.alter_column('animals', 'status',
               existing_type=mysql.ENUM('alive', 'sold', 'dead', 'transferred'),
               nullable=False)
    op.alter_column('animals', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('curdate()'))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('curdate()'))
    op.alter_column('animals', 'status',
               existing_type=mysql.ENUM('alive', 'sold', 'dead', 'transferred'),
               nullable=True)
    op.alter_column('animals', 'source',
               existing_type=mysql.ENUM('birth', 'purchase'),
               nullable=True)
    op.alter_column('animals', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('animals', 'breed',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('animals', 'species',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('animals', 'tag_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('animals', 'updated_at')
    # ### end Alembic commands ###
