"""fields added to material table

Revision ID: 6d42c88042aa
Revises: 28f062286d7b
Create Date: 2025-12-27 19:33:10.825882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d42c88042aa'
down_revision = '28f062286d7b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_inventory_moves', sa.Column('is_move_to_inventory', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_inventory_moves', 'is_move_to_inventory')
    # ### end Alembic commands ###
