"""fields added to material table

Revision ID: 7adcb131b49e
Revises: 3d1efdbe9fe5
Create Date: 2025-12-26 21:08:16.722454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adcb131b49e'
down_revision = '3d1efdbe9fe5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_raw_materials', sa.Column('material_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_raw_materials', 'material_description')
    # ### end Alembic commands ###
