"""refactor models to common

Revision ID: 958828c6db3e
Revises: d55b6d8f69cd
Create Date: 2025-12-31 10:27:42.329771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958828c6db3e'
down_revision = 'd55b6d8f69cd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
