"""established_relation lazy selectin

Revision ID: 98ac8a75b4da
Revises: 7081420032b9
Create Date: 2025-12-25 19:25:45.406111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98ac8a75b4da'
down_revision = '7081420032b9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_events', 'event_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('animal_events_ibfk_1'), 'animal_events', type_='foreignkey')
    op.create_foreign_key(None, 'animal_events', 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
    op.alter_column('animal_inventory_moves', 'movement_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('animal_inventory_moves_ibfk_1'), 'animal_inventory_moves', type_='foreignkey')
    op.create_foreign_key(None, 'animal_inventory_moves', 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purchase_raw_materials', 'type_of_material',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('purchase_raw_materials', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('purchase_raw_materials', 'unit_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('purchase_raw_materials', 'total_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_raw_materials', 'total_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('purchase_raw_materials', 'unit_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('purchase_raw_materials', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('purchase_raw_materials', 'type_of_material',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'animal_inventory_moves', type_='foreignkey')
    op.create_foreign_key(op.f('animal_inventory_moves_ibfk_1'), 'animal_inventory_moves', 'animals', ['animal_id'], ['id'])
    op.alter_column('animal_inventory_moves', 'movement_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'animal_events', type_='foreignkey')
    op.create_foreign_key(op.f('animal_events_ibfk_1'), 'animal_events', 'animals', ['animal_id'], ['id'])
    op.alter_column('animal_events', 'event_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
