"""profile url added

Revision ID: a153f587a4fd
Revises: 3c7cd980e481
Create Date: 2026-02-10 13:23:23.779274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a153f587a4fd'
down_revision = '3c7cd980e481'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_tracking', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('customers', sa.Column('customer_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'customer_image')
    op.drop_column('animal_tracking', 'image_url')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###