"""master animal table

Revision ID: a4166e0b3c68
Revises: 6d42c88042aa
Create Date: 2025-12-31 09:44:20.706690

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a4166e0b3c68"
down_revision = "6d42c88042aa"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop constraints on child tables first
    # op.drop_constraint(
    #     op.f("animal_events_ibfk_1"), "animal_events", type_="foreignkey"
    # )
    # op.drop_constraint(
    #     op.f("animal_inventory_moves_ibfk_1"),
    #     "animal_inventory_moves",
    #     type_="foreignkey",
    # )

    # 2. Create new table
    op.create_table(
        "animal_tracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.String(length=50), nullable=False),
        sa.Column("main_animal_id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("birth", "purchase", name="animalsource", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_reference", sa.String(length=100), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "alive",
                "sold",
                "dead",
                "transferred",
                "in_inventory",
                name="animalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("inventory_moved_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_animal_tracking_id"), "animal_tracking", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_animal_tracking_main_animal_id"),
        "animal_tracking",
        ["main_animal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_animal_tracking_tag_id"), "animal_tracking", ["tag_id"], unique=True
    )

    # 3. Drop old table
    # op.drop_index(op.f("ix_animals_id"), table_name="animals")
    # op.drop_index(op.f("ix_animals_tag_id"), table_name="animals")
    op.drop_table("animals")

    # 4. Create new FKs
    op.create_foreign_key(
        None,
        "animal_events",
        "animal_tracking",
        ["animal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "animal_inventory_moves",
        "animal_tracking",
        ["animal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "animal_inventory_moves", type_="foreignkey")
    op.create_foreign_key(
        op.f("animal_inventory_moves_ibfk_1"),
        "animal_inventory_moves",
        "animals",
        ["animal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "animal_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("animal_events_ibfk_1"),
        "animal_events",
        "animals",
        ["animal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "animals",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("tag_id", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("species", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("breed", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("gender", mysql.VARCHAR(length=10), nullable=False),
        sa.Column("birth_date", sa.DATE(), nullable=True),
        sa.Column("source", mysql.VARCHAR(length=8), nullable=False),
        sa.Column("source_reference", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("purchase_price", mysql.FLOAT(), nullable=True),
        sa.Column(
            "status",
            mysql.VARCHAR(length=12),
            server_default=sa.text("'alive'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.Column("purchase_date", sa.DATE(), nullable=True),
        sa.Column("inventory_moved_date", sa.DATE(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_animals_tag_id"), "animals", ["tag_id"], unique=True)
    op.create_index(op.f("ix_animals_id"), "animals", ["id"], unique=False)
    op.drop_index(op.f("ix_animal_tracking_tag_id"), table_name="animal_tracking")
    op.drop_index(
        op.f("ix_animal_tracking_main_animal_id"), table_name="animal_tracking"
    )
    op.drop_index(op.f("ix_animal_tracking_id"), table_name="animal_tracking")
    op.drop_table("animal_tracking")
    # ### end Alembic commands ###
