"""purchase and enum set on 24_12_25

Revision ID: a8bd165fcb99
Revises: 6141d38f2700
Create Date: 2025-12-24 15:27:53.542993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8bd165fcb99'
down_revision = '6141d38f2700'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.alter_column('animals', 'source',
               existing_type=mysql.ENUM('birth', 'purchase'),
               type_=sa.Enum('birth', 'purchase', name='animalsource', native_enum=False),
               existing_nullable=False)
    op.alter_column('animals', 'status',
               existing_type=mysql.ENUM('alive', 'sold', 'dead', 'transferred'),
               type_=sa.Enum('alive', 'sold', 'dead', 'transferred', name='animalstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'alive'"))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'status',
               existing_type=sa.Enum('alive', 'sold', 'dead', 'transferred', name='animalstatus', native_enum=False),
               type_=mysql.ENUM('alive', 'sold', 'dead', 'transferred'),
               existing_nullable=False,
               existing_server_default=sa.text("'alive'"))
    op.alter_column('animals', 'source',
               existing_type=sa.Enum('birth', 'purchase', name='animalsource', native_enum=False),
               type_=mysql.ENUM('birth', 'purchase'),
               existing_nullable=False)
    op.drop_column('animals', 'purchase_date')
    # ### end Alembic commands ###
