"""make customer firstname phone email not null

Revision ID: afb3a6733369
Revises: 1cef25474658
Create Date: 2025-11-28 15:20:25.323017

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afb3a6733369'
down_revision = '1cef25474658'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
