"""fields added to material table

Revision ID: b740f4fb4a40
Revises: 7adcb131b49e
Create Date: 2025-12-26 21:50:17.115926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b740f4fb4a40'
down_revision = '7adcb131b49e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_raw_materials', sa.Column('gross_price', sa.Float(), nullable=False))
    op.add_column('purchase_raw_materials', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('purchase_raw_materials', sa.Column('discount_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_raw_materials', 'discount_percentage')
    op.drop_column('purchase_raw_materials', 'discount_amount')
    op.drop_column('purchase_raw_materials', 'gross_price')
    # ### end Alembic commands ###
