"""new tables

Revision ID: bbd3e3f49681
Revises: 
Create Date: 2026-02-03 21:37:43.061390

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'bbd3e3f49681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', 'created_by', name='uq_animals_sku_created_by'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column(
        'updated_at', 
        sa.TIMESTAMP(), 
        server_default= sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
        nullable=True
        ),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'created_by', name='uq_customers_email_created_by'),
    sa.UniqueConstraint('phone', 'created_by', name='uq_customers_phone_created_by'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('post_offices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('circlename', sa.String(length=64), nullable=True),
    sa.Column('regionname', sa.String(length=64), nullable=True),
    sa.Column('divisionname', sa.String(length=64), nullable=True),
    sa.Column('officename', sa.String(length=64), nullable=True),
    sa.Column('pincode', sa.String(length=64), nullable=True),
    sa.Column('officetype', sa.String(length=64), nullable=True),
    sa.Column('delivery', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('statename', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.Text(), nullable=False),
    sa.Column('type_of_material', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('material_expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.Text(), nullable=True),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gross_price', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column(
        'created_at', 
        sa.TIMESTAMP(), 
        server_default= sa.text('CURRENT_TIMESTAMP'), 
        nullable=False
        ),
    sa.Column(
        'updated_at', 
        sa.TIMESTAMP(), 
        server_default= sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
        nullable=True
        ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'created_by', name='uq_inventory_animal_id_created_by'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('order_verification_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('shipping', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('placed_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column(
        'created_at', 
        sa.TIMESTAMP(), 
        server_default=sa.text('CURRENT_TIMESTAMP'), 
        nullable=False
        ),
    sa.Column(
        'updated_at', 
        sa.TIMESTAMP(), 
        server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
        nullable=True
        ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('gross_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column(
        'created_at', 
        sa.TIMESTAMP(), 
        server_default=sa.text('CURRENT_TIMESTAMP'), 
        nullable=False
        ),
    sa.Column(
        'updated_at', 
        sa.TIMESTAMP(), 
        server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
        nullable=True
        ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('animal_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('birth', 'purchase', name='animalsource', native_enum=False), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('alive', 'sold', 'dead', 'transferred', 'in_inventory', name='animalstatus', native_enum=False), nullable=False),
    sa.Column('inventory_moved_date', sa.Date(), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_status', sa.Enum('null', 'pending', 'in_transit', 'delivered', 'cancelled', name='orderstatus', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['animals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_animal_tracking_category_id'), 'animal_tracking', ['category_id'], unique=False)
    op.create_index(op.f('ix_animal_tracking_id'), 'animal_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_animal_tracking_tag_id'), 'animal_tracking', ['tag_id'], unique=True)
    op.create_table('animal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('milk_quantity', sa.Float(), nullable=True),
    sa.Column('milk_rate', sa.Float(), nullable=True),
    sa.Column('milk_snf', sa.Float(), nullable=True),
    sa.Column('milk_fat', sa.Float(), nullable=True),
    sa.Column('milk_time', sa.String(length=50), nullable=True),
    sa.Column('milk_water', sa.Float(), nullable=True),
    sa.Column('milk_session', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_animal_events_animal_id'), 'animal_events', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_events_event_date'), 'animal_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_animal_events_event_type'), 'animal_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_animal_events_id'), 'animal_events', ['id'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_fat'), 'animal_events', ['milk_fat'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_quantity'), 'animal_events', ['milk_quantity'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_rate'), 'animal_events', ['milk_rate'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_session'), 'animal_events', ['milk_session'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_snf'), 'animal_events', ['milk_snf'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_time'), 'animal_events', ['milk_time'], unique=False)
    op.create_index(op.f('ix_animal_events_milk_water'), 'animal_events', ['milk_water'], unique=False)
    op.create_table('animal_inventory_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('is_move_to_inventory', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_animal_inventory_moves_animal_id'), 'animal_inventory_moves', ['animal_id'], unique=False)
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=255), nullable=False),
    sa.Column('firstname', app.models.user_tables.EncryptedString(length=1024), nullable=False),
    sa.Column('lastname', app.models.user_tables.EncryptedString(length=1024), nullable=True),
    sa.Column('username', app.models.user_tables.EncryptedString(length=1024), nullable=False),
    sa.Column('email', app.models.user_tables.EncryptedString(length=1024), nullable=False),
    sa.Column('mobile', app.models.user_tables.EncryptedString(length=1024), nullable=False),
    sa.Column('hashed_username', sa.String(length=255), nullable=False),
    sa.Column('hashed_email', sa.String(length=255), nullable=False),
    sa.Column('hashed_mobile', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('old_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_create_at', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_welcome_mail_sent', sa.Boolean(), nullable=False),
    sa.Column('is_password_change_mail_sent', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_file_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_hashed_email'), 'users', ['hashed_email'], unique=True)
    op.create_index(op.f('ix_users_hashed_mobile'), 'users', ['hashed_mobile'], unique=True)
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_hashed_username'), 'users', ['hashed_username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_old_password'), 'users', ['old_password'], unique=False)
    op.create_index(op.f('ix_users_password_create_at'), 'users', ['password_create_at'], unique=False)
    op.create_index(op.f('ix_users_unique_id'), 'users', ['unique_id'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###

def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_inventory_moves_animal_id'), table_name='animal_inventory_moves')
    op.drop_table('animal_inventory_moves')
    op.drop_index(op.f('ix_animal_events_milk_water'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_time'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_snf'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_session'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_rate'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_quantity'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_milk_fat'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_id'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_event_type'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_event_date'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_animal_id'), table_name='animal_events')
    op.drop_table('animal_events')
    op.drop_index(op.f('ix_animal_tracking_tag_id'), table_name='animal_tracking')
    op.drop_index(op.f('ix_animal_tracking_id'), table_name='animal_tracking')
    op.drop_index(op.f('ix_animal_tracking_category_id'), table_name='animal_tracking')
    op.drop_table('animal_tracking')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('deliveries')
    op.drop_table('orders')
    op.drop_table('order_verification_tokens')
    op.drop_table('inventory')
    op.drop_table('addresses')
    op.drop_table('purchase_raw_materials')
    op.drop_table('post_offices')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('animals')
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_unique_id'), table_name='users')
    op.drop_index(op.f('ix_users_password_create_at'), table_name='users')
    op.drop_index(op.f('ix_users_old_password'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_username'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_email'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###