"""refactor models to common

Revision ID: bc2a7e67307e
Revises: 958828c6db3e
Create Date: 2025-12-31 10:31:58.722128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2a7e67307e'
down_revision = '958828c6db3e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_default():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_tracking():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
