"""make addressess city state country postal code not null

Revision ID: f31d9c554c41
Revises: afb3a6733369
Create Date: 2025-11-28 15:27:02.803293

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'f31d9c554c41'
down_revision = 'afb3a6733369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresses', 'postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('addresses', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresses', 'postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('addresses', 'state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresses', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
